### ISSUE TITLE
В списке дедлайнов как-то помечать, что контест уже сдан

### ISSUE THREAD

**Issue by lodthe** [DarkKeks/kks#100]
Когда использую kks deadlines, непонятно, есть ли еще не сданные задачи в каком-то контесте.

Не знаю, как это сделать норм, то можно, например, поставить звездочку рядом с тем контестом, в который еще можно что-то заслать.

cc @vvd170501

**Comment by DarkKeks** [comment]
Либо можно контесты, которые полностью закрыты, выделять красным, как и контесты по которым прошли дедлайны
Чтобы цветом выделялись только контесты, с которыми еще надо что-то делать

**Comment by vvd170501** [comment]
> поставить звездочку рядом с тем контестом, в который еще можно что-то заслать

Скорее всего, будет плохо заметно

> выделять красным, как и контесты по которым прошли дедлайны

Не уверен, что это хорошая идея - визуально сложно отличить контесты с прошедшим дедлайном и решённые
![Screenshot_20210401-152644~3](https://user-images.githubusercontent.com/36827317/113293859-fb46c600-92fe-11eb-83ac-ecf1b7703993.png)

Ещё один вариант - выделять серым (`bright_black`)
![Screenshot_20210401-152359~2](https://user-images.githubusercontent.com/36827317/113293918-0e599600-92ff-11eb-9797-191a10a2749a.png)

Если такой вариант выглядит нормально - могу добавить

**Comment by DarkKeks** [comment]
Мне нравится 👍

**Comment by DarkKeks** [comment]
А может пойти еще дальше?
Добавить в `kks status` колонку с дедлайном и фильтр по "решенности"?

Тогда достаточно будет сделать `kks status --todo??` чтобы понять какие задачи осталось сдать
Вместо того чтобы сопоставлять дедлайны контестов с нерешенными задачами

Я бы активно пользовался :)

**Comment by vvd170501** [comment]
> Добавить в `kks status` колонку с дедлайном

Не уверен, что это хорошая идея.
1) Цвет уже используется для статуса задач -> показать наличие / близость дедлайна можно только текстом
2) Добавляется ещё одна колонка, значения в которой совпадают для всех задач из одного контеста. Получаем "стену текста", в которой, например, сложно заметить различные дедлайны у соседних контестов
3) Для показа статуса придётся парсить дедлайны (если их нет в кеше) -> возможно замедление работы. 

Насчёт второго пункта - можно попробовать добавить разделитель между контестами, чтобы улучшить читаемость (даже если не добавлять столбец с дедлайнами). Правда, пока непонятно, как должен выглядеть вывод, если используются фильтры по контестам / задачам

> `kks status --todo??` чтобы понять какие задачи осталось сдать

Такой вариант выглядит лучше - можно загружать дедлайны только при вызове `kks status` с этим флагом, т.е. 3-й пункт не является проблемой. Опять же, в таком случае нужно понять, каким должен быть формат таблицы.
