### ISSUE TITLE
Фильтр по несданным задачам в "kks status"

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#103]
См. https://github.com/DarkKeks/kks/issues/100#issuecomment-811995951, https://github.com/DarkKeks/kks/issues/100#issuecomment-812014773

По идее, стоит вынести загрузку дедлайнов из `kks.cmd.deadlines` в общий модуль (`kks.ejudge`?)

Условие фильтра должно быть примерно таким:
```python3
not first_problem.past_deadline() and problem.status in [Status.NOT_SUBMITTED, Status.PARTIAL, Status.REJECTED]
```

**Comment by DarkKeks** [comment]
В каком-то виде дедлайны все равно хочется :/
Иначе все равно придется смотреть в несколько мест чтобы понять что решать приоритетней
