### ISSUE TITLE
kks status --todo не отображает реджектнутые таски по которым прошёл дедлайн

### ISSUE THREAD

**Issue by SphericalPotatoInVacuum** [DarkKeks/kks#112]
* Ожидаемое поведение: сделать надо бы все задачи, по которым пришёл реджект, а значит и показывать их тоже надо
* Реальное поведение: реджектнутые задачи, по которым уже прошёл дедлайн, не показываются

Пришедший реджект:
![image](https://user-images.githubusercontent.com/25670500/113523510-85698580-95b0-11eb-97e2-7cb5b6f54b74.png)

Отсутствие реджекта в --todo:
![image](https://user-images.githubusercontent.com/25670500/113523519-90bcb100-95b0-11eb-95e6-25271cbebc1d.png)

Самое интересное что до жёсткого дедлайна ещё 3 дня (сейчас 2021.04.05, 01:48):
![image](https://user-images.githubusercontent.com/25670500/113523570-dbd6c400-95b0-11eb-8fe4-f4ae15d66d57.png)

**Comment by vvd170501** [comment]
Насчёт отображения реджектнутых задач после дедлайна - добавлю.

Насчёт несовпадения дедлайнов - kks считает, что дедлайн прошёл, если прошла дата жёсткого дедлайна или текущий штраф больше или равен полному баллу за задачу
На скриншоте - второй случай. Если окажется, что с таким штрафом можно сдать _не сданную ранее_ задачу с ненулевым баллом, значит, придётся учитывать только жёсткие дедлайны.

**Comment by vvd170501** [comment]
Также не совсем понятно, как сортировать реджектнутые задачи по дате. Они могут оставаться открытыми даже после жёсткого дедлайна, но непонятно, есть ли какой-то отдельный дедлайн для таких задач. Если его нет - есть смысл ставить такие задачи в конец списка.

**Comment by vvd170501** [comment]
Если предполагать, что отдельного дедлайна для реджектов не существует, получается примерно такая таблица:
![Screenshot_20210405-024002~2](https://user-images.githubusercontent.com/36827317/113524586-58b96c00-95b8-11eb-9ff8-e3345e2b2895.png)

Нужно ли в таком случае выделять красным статус `Past deadline`, или лучше использовать какой-то другой формат?

**Comment by vvd170501** [comment]
Насчёт штрафов и дедлайнов.
Если посмотреть на результат, возвращаемый методом `API.problem_status`, у большинства (всех?) задач из обычных контестов есть 2 поля - `min_score_1` (равное 50) и `min_score_2` (равное 20). Судя по [этому комментарию](https://github.com/blackav/ejudge/blob/5a0d7cc1bb7d3403115d80a9941fe86c4e578e96/include/ejudge/prepare.h#L812) и [этому коду](https://github.com/blackav/ejudge/blob/5a0d7cc1bb7d3403115d80a9941fe86c4e578e96/lib/html.c#L177), второе поле обозначает минимальный балл с учётом _всех_ штрафоа. Получается, что со штрафом, большим или равным полному баллу, задачу все равно можно сдать с ненулевым баллом.

**Comment by SphericalPotatoInVacuum** [comment]
> Если предполагать, что отдельного дедлайна для реджектов не существует, получается примерно такая таблица:
> ![Screenshot_20210405-024002~2](https://user-images.githubusercontent.com/36827317/113524586-58b96c00-95b8-11eb-9ff8-e3345e2b2895.png)
> 
> Нужно ли в таком случае выделять красным статус `Past deadline`, или лучше использовать какой-то другой формат?

Возможно в случае реджекта дедлайн можно выделять серым или подобным нейтральным цветом, потому что задача по факту уже сдана, и дедлайн теперь не самое важное

**Comment by vvd170501** [comment]
Добавил серый цвет для прошедших дедлайнов, теперь выглядит так:
![Screenshot_20210405-142242~2](https://user-images.githubusercontent.com/36827317/113569182-b5e60980-961a-11eb-81bd-8ce54120bc98.png)

Для задач, у которых дедлайн ещё не прошёл / отсутствует, цвет не меняется - иначе в таблице получается слишком много цветов и она становится менее читаемой

**Comment by SphericalPotatoInVacuum** [comment]
Как по мне выглядит ~идеально
