### ISSUE TITLE
[feature request] Скачивание исходного кода при синхронизации с ejudge

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#12]
Возможно, стоило бы добавить в команду "kks sync" скачивание исходного кода отправленных ранее решений (например, может пригодиться для использования кода из ДЗ на КР). 
Альтернативный вариант - добавить для этого отдельную команду.

**Comment by DarkKeks** [comment]
Тогда это должно быть либо аргументом в sync, либо отдельной командой, чтобы по умолчанию sync не делал лишних запросов

Хранить посылки можно в отдельной папке (например, `sm01/1/submissions/1-OK.c`)
Думаю полезно иметь в названии файла вердикт, например `1-Rejected.c` или `2-WA7.c`

**Comment by vvd170501** [comment]
Ок, попробую сделать вариант с  аргументом

**Comment by vvd170501** [comment]
Добавлено в #13
