### ISSUE TITLE
Ошибка линковки для многопоточных решений при отключенном санитайзере

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#121]
При попытке компиляции многопоточного решения (команды `build` / `run` / `test`) с использованием опции `--no-asan` линковщик выдаёт ошибку (т.к. не производится линковка с `libpthread`).

Варианты решения проблемы:
 - Добавить флаг `-pthread` в дефолтный таргет. По идее, это не должно влиять на скорость компиляции, если многопоточность не используется.
 - Добавлять флаг к используемым опциям, если в названии задачи встречается `/pthread/` (`/thread/`).
Если будет проводиться КР на многопоточность, этот вариант для неё не сработает.
 - Добавить отдельный таргет для многопоточных решений. Минусы - придётся явно указывать таргет при компиляции / запуске решения, нужно опять переписывать (или полностью дописывать) логику компиляции C++-решений.

**Comment by DarkKeks** [comment]
> Добавить флаг -pthread в дефолтный таргет. По идее, это не должно влиять на скорость компиляции, если многопоточность не используется.

А какие минусы есть кроме врмени компиляции? Если действительно боишься что может стать медленней, то пробегись по своим решениями, померяй время до и после, посмотри на разницу :)

Если кажется, что разница ощутимая, то я за второй вариант

**Comment by vvd170501** [comment]
Проверил, использование флага не влияет на скорость компиляции. Если первый вариант (сама идея) выглядит нормально - добавлю

**Comment by DarkKeks** [comment]
> Проверил, использование флага не влияет на скорость компиляции. Если первый вариант (сама идея) выглядит нормально - добавлю

Мне ок 👍
