### ISSUE TITLE
Не работает kks top --global

### ISSUE THREAD

**Issue by ElderlyPassionFruit** [darkkeks/kks#128]
Failed to send standings to kks api
Failed to receive global standings: HTTPSConnectionPool(host='kks.darkkeks.me', port=443): Max retries exceeded with url: /api/get?year=2021&contest_id=203&login=bpmi203-129 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
Standings are not available now :(

**Comment by SenchoPens** [comment]
У меня сейчас работает, тогда, видимо, просто kks.darkkeks.me упал или серт просрочился. @vvd170501, закроешь?

**Comment by vvd170501** [comment]
Похоже на какую-то локальную проблему (возможно, подмена сертификата на уровне провайдера?). У меня в тот день доступ к API работал.

Если проблема возникнет снова и будет связана с kks, можно переоткрыть issue или создать новый.
