### ISSUE TITLE
А когда появится возможность автоматического решения задач с курса АКОС?

### ISSUE THREAD

**Issue by ruct** [DarkKeks/kks#19]

**Comment by DarkKeks** [comment]
Крутая идея! К сожалению нету сейчас возможности реализовать самому :(

**Comment by LoDThe** [comment]
Так на почту решения присылают же

**Comment by DarkKeks** [comment]
Может добавить `kks share`? :thinking:

**Comment by LoDThe** [comment]
> Может добавить `kks share`?

Чтобы оно раздачу в торренте начинало и на рутрекере тред создавало.
