### ISSUE TITLE
(лишний?) бэкслэш перед пробелом

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#24]
https://github.com/DarkKeks/kks/blob/a08956a7261c0c372c2c41808ef842626633d34b/kks/util.py#L177

**Comment by DarkKeks** [comment]
Повторял за `git diff`
<img width="396" alt="image" src="https://user-images.githubusercontent.com/13303874/101724283-4bcfb480-3abf-11eb-82dd-afc86a5531ab.png">

**Comment by vvd170501** [comment]
Тогда должно быть так: `'\n\\ No newline at end of file'` (в текущем варианте бэкслэш не экранирован)

**Comment by vvd170501** [comment]
Исправлено в #25

**Comment by DarkKeks** [comment]
Неправда же, `print('\ ')` будет выводить `\ `, потому что пробел не экранируется

**Comment by vvd170501** [comment]
Линтер говорит, что это "invalid escape sequence", в будущем это может стать ошибкой синтаксиса (https://www.flake8rules.com/rules/W605.html)
