### ISSUE TITLE
Слишком много предупреждений при повторной синхронизации

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#27]
При запуске синхронизации выводится предупреждение для каждой ранее синхронизированной задачи. Учитывая то, что к концу года задач будет намного больше, стоит как-то изменить вывод (см. https://github.com/DarkKeks/kks/issues/25#issuecomment-743278434)

Также для скрытых контестов выводится путь до папки контеста относительно корневой директории (например, `.kks-contests/sm01/1`), что тоже значительно увеличивает длину вывода (см. https://github.com/DarkKeks/kks/pull/25#issuecomment-743274773)

**Comment by vvd170501** [comment]
Возможные варианты решения первой проблемы:
* Игнорировать уже синхронизированные задачи (нет лишнего вывода, но непонятно, какие контесты были синхронизированы)
* Выдавать по одному предупреждению для каждого контеста (в этом случае видно, что они были синхронизированы, но остаётся достаточно много лишнего текста (к концу года должно существовать около 30 контестов)) 
* Убрать предупреждения, использовать прогрессбар (чтобы было видно количество контестов) (вряд ли хорошая идея, т.к. для существующих контестов синхронизация пропускается почти моментально)

Варианты решения второй проблемы, если для существующих контестов останется какой-то вывод:
* Выводить путь относительно скрытой папки (`.kks-contests`)
* Не показывать предупреждения для скрытых контестов (т.е. `hide` будет относиться и к файловой системе, и к выводу при синхронизации)

Возможно, существуют какие-то более оптимальные варианты, чем все предложенное выше

**Comment by DarkKeks** [comment]
Я бы варнинги просто убрал)

И тогда можно в конце какое нибудь сообщение добавить с количеством задач которые добавлены/уже существовали

**Comment by vvd170501** [comment]
Ок, можно и так. Попробую реализовать

**Comment by vvd170501** [comment]
Добавлено в #28
