### ISSUE TITLE
Синхронизация условий задач

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#30]
Было бы хорошо добавить синхронизацию условий вместе с семплами.
Например, это позволит полностью взаимодействовать с ejudge чеез терминал (наверное, единственное, что нельзя будет сделать без использования браузера &mdash; отправка/получение сообщений).
Для синхронизации не потребуется дополнительных запросов к ejudge, т.к. для семпла уже запрашивается полная страница с задачей.

**Comment by DarkKeks** [comment]
Было бы удобно

Особенно круто было бы парсить ejudge и преобразовывать в какой нибудь `.md`, чтобы оно выглядело красиво (особенно если потом сохранить рабочую копию на какой нибудь гитхаб)

Но и просто сохранять текст тоже полезно

**Comment by vvd170501** [comment]
Пока неясно, что делать с ранее синхронизированными задачами. Можно их игнорировать (тогда условия будут сохранены только для новых задач, это не очень хорошо). Или можно добавить какой-нибудь флаг типа `--force`, чтобы принудительно синхронизировать старые задачи.
Ещё один вариант - добавить что-то типа "версии" воркспейса (для случая, если структура директорий будет ещё когда-нибудь меняться). Если текущая версия не самая новая - можно запускать принудительную синхронизацию по умолчанию и обновлять версию

**Comment by DarkKeks** [comment]
Я бы добавил `--force`
Семплы тоже полезно перекачать (мне уже пару раз пригодилось бы)

Вариант с версией мне не нравится тем, что придется еще что-то хранить для воркспейса, но применение пока неочень полезное)

Заодно даем выбор, докачивать условия, или не трогать старые задачи

**Comment by DarkKeks** [comment]
Ну и сам по себе --force полезный, если хочется явно перекачать что-либо, например из-за обновления условия в ejudge
