### ISSUE TITLE
Неиспользуемая опция "--ignore-exit-code" в команде "gen"

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#32]
Опция `--ignore-exit-code` в команде `kks gen` используется только для объекта класса `TestSource`, в котором она ни на что не влияет. Если флаг добавлен к этой команде по ошибке, а не с расчетом на добавление функционала в будущем, то его стоит удалить.

**Comment by vvd170501** [comment]
Для самого класса `TestSource` атрибут `ignore_exit_code` тоже имеет мало смысла, т.к. он нужен только при итерации по тестам, а не при генерации ввода/вывода

**Comment by DarkKeks** [comment]
Да, забыл в паре мест дописать 🤡 

Сейчас должно быть норм
