### ISSUE TITLE
Добавить поддержку тестирования *.c файлов с различными main

### ISSUE THREAD

**Issue by territhing** [DarkKeks/kks#39]
Хочецца иметь main для отладки и main для контеста, а их не завезли...

**Comment by DarkKeks** [comment]
Можно тупо добавить какое нибудь `--kekos first.c --kekos second.c` и компилировать только их, а не `*.c`

Либо можно какие нибудь стремные варианты попридумывать, вида 
- позволить собирать мейкфайлом, указывая таргет (только я в make не умею, и мне неочевидно откуда брать бинарник)
- сделать кастомный конфиг для задачи, в котором создавать таргеты с аргументами компилятора и файлами, либо просто строкой компиляции

Оба варианта полезны для асма, так как там скорее всего будет полезно кастомные строки компиляции писать (?)

Может @vvd170501 еще какой нибудь вариант предложит 👀

**Comment by vvd170501** [comment]
Первый вариант (с именами файлов в аргументах) получится слишком ограниченным. 
Возможная ситуация: в решении используется один файл, в нём отладочный код обёрнут в `#ifdef DBG`. При компиляции нет возможности передать gcc нужный макрос (в `kks run` все дополнительные аргументы передаются уже скомпилированному бинарнику). Такая же проблема может быть и с асмом.
В варианте с make появляется дополнительная зависимость + не все знают его синтаксис.
Вариант с конфигом выглядит интересно, но в таком случае нужно понять, какие опции он должен поддерживать (предположительно, флаги компилятора/линкера, списки файлов и таргеты).

**Comment by vvd170501** [comment]
Добавил конфиг в #45
@territhing, @DarkKeks может быть, есть идеи, как это улучшить?
