### ISSUE TITLE
Не работает header

### ISSUE THREAD

**Issue by maximkm** [DarkKeks/kks#4]
Если написать программу с функцией для контеста, а потом подключить её в main.c через #include "name.c" для тестов, то будет ошибка:
![image](https://user-images.githubusercontent.com/33720039/99597933-d31e9080-2a09-11eb-8693-7dea7783e4ef.png)

**Comment by DarkKeks** [comment]
На самом деле непонятно как было бы правильней компилировать по умолчанию

Прямо сейчас компилируется `*.c`, из-за чего функция в твоём случае повторяется два раза.
Один раз в `name.c`, а другой -- как часть `main.c`

Варианты как компилировать сейчас:
- переименовать `name.c` в `name.h`
- в `main.c` не инклюдить файл, а написать лишь заголовок функции
- писать все в одном файле

Как пофиксить это более системно я подумаю :)

**Comment by maximkm** [comment]
При условии, что в контест можно засылать файлы формата `.h`, то самое правильное просто называть файл `name.h`. Нет смысла фиксить для формата `.c`.
