### ISSUE TITLE
Скрытые части условия

### ISSUE THREAD

**Issue by DarkKeks** [DarkKeks/kks#51]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/13303874/105541987-adfc1600-5d09-11eb-80c2-e47882bf9182.png">

**Comment by DarkKeks** [comment]
@vvd170501 😆

**Comment by vvd170501** [comment]
Можно добавить в `h2t` обработчик для таких тегов - например, вставлять комментарий, что этот блок текста скрыт. Может быть полезно, если скрытой оказалась ошибочная / устаревшая часть условия

**Comment by vvd170501** [comment]
Добавлено в #53
