### ISSUE TITLE
Вынести скачивание (и конвертацию в md) задач с Ejudge отдельно

### ISSUE THREAD

**Issue by territhing** [DarkKeks/kks#55]
Запрос для очень актуальной фичи, учитывая классный (🤡) формат контрольных

**Comment by vvd170501** [comment]
Не совсем понятно, что именно нужно добавлять. Скачивание уже есть и работает.

Насчёт недоступности условий КР из браузера - доступ был через ssh + ejudge-fuse.
Если проблема решалась только использованием ejudge-fuse, то можно попробовать использовать [этот скрипт](https://github.com/vvd170501/kks/blob/api-dl-test/api_statements.py) - он использует такой же метод доступа к API, как и ejudge-fuse (для скрипта нужна версия kks из vvd170501/kks@95c844fba7eb9da863b48fc05e69aebdee124f16)
Если ограничение на условия работало по IP (такое возможно?) - в таком случае ничего не поможет, придётся использовать ssh

**Comment by DarkKeks** [comment]
> такое возможно

Лень сейчас проверять, но видел около кр какой то коммит в ejudge, похожий на ограчниение по IP

Против такого можно попробовать сделать ssh тоннель на сервер :eyes:

**Comment by DarkKeks** [comment]
> Не совсем понятно, что именно нужно добавлять

Я понял как "добавить возможность сконвертировать условия из html в md отдельной командой"
Чтобы делать, например, `scp ... && kks convert ...`
