### ISSUE TITLE
Перевод строки в конце семплов

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#59]
В некоторых задачах (по крайней мере, sm10-1), не требуется перевод строки в конце вывода.
`kks sync` всегда добавляет перевод строки к примерам из условия (на этой задаче корректное решение не пройдёт тестирование через `kks test`).
Есть ли смысл что-то с этим делать?

**Comment by DarkKeks** [comment]
"Не пройдет тестирование" &mdash; это не плохой вариант. Как минимум потому, что заставит задуматься, правильно ли ты понял условие. И при необходимости пофиксить семпл

Плохой вариант &mdash; это когда тесты прошли, но с неправильным семплом
Если нету способа определять нужен ли `\n`, мне кажется лучше всегда добавлять

**Comment by vvd170501** [comment]
Ок, тогда закрываю
