### ISSUE TITLE
Код завершения команды "kks run"

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#61]
Сейчас (версия kks 1.9.0) команда `kks run` всегда завершается с кодом 0.
Возможно, правильнее будет завершать работу команды с тем же кодом, который возвращает скомпилированное и запущенное решение.
Тогда будет иметь смысл (например) такой вариант запуска: `kks run || echo RE`

**Comment by DarkKeks** [comment]
Давай, лишним не будет :)
