### ISSUE TITLE
Неполная глобальная таблица

### ISSUE THREAD

**Issue by vvd170501** [DarkKeks/kks#74]
Новые контесты отображаются только у тех групп, которые отправляли на сервер статистику после добавления контеста.
Из-за этого некорректно работает подсчёт максимальных баллов (возможно получить разницу в 500 баллов, которой на самом деле нет).
![Screenshot from 2021-02-13 17-47-20](https://user-images.githubusercontent.com/36827317/107853184-9a822d80-6e25-11eb-9be5-ef5b90190739.png)
(например, 306 и 308 строки - без опции `--max` у обоих пользователей 0 баллов)

Решение - добавлять новые контесты (с пустыми статусами задач) для всех групп.
Это можно реализовать как на стороне сервера, так и на стороне клиента.

**Comment by DarkKeks** [comment]
Поправлю на сервере

**Comment by DarkKeks** [comment]
Done https://github.com/DarkKeks/telegram-bots/commit/2da5089b534f7151102224e9e18b1103ae586e99
