### ISSUE TITLE
Не работают аргументы с kks gen

### ISSUE THREAD

**Issue by rybbba** [DarkKeks/kks#79]
При запуске ```kks gen``` c указанием аргументов (например ```kks gen 1```), происходит вылет с ошибкой 
```
File "/home/user/.local/lib/python3.9/site-packages/kks/util/testing.py", line 26, in generate_input
    args = [test] + (additional_args or [])
TypeError: can only concatenate list (not "tuple") to list
```
python 3.9.1

**Comment by DarkKeks** [comment]
Думаю стоит совсем выпилить, раз это обнаружили только сейчас, и то случайно
Без этого будет показываться нормальный help
Для ситуации "случайно передал арги без опции" это полезней))
