### ISSUE TITLE
Отображение символов окончания строки/табов/пробелов и т.д. в диффе при тестировании

### ISSUE THREAD

**Issue by SphericalPotatoInVacuum** [DarkKeks/kks#8]
При тестировании часто можно налететь на вот такую ситуацию: в правильном выводе в конце строки должен стоять '\n', но мы по ошибке решили вывести ' '. При этом понять, а что именно, собственно, не так, удаётся не сразу.

![image](https://user-images.githubusercontent.com/25670500/100253876-b37bf080-2f52-11eb-9ddb-841ca2bfc601.png)

Предложение: возможно в таких случаях (ну или всегда) стоит как-то explicitly показывать, что от нас требуется перевод строки, а мы вместо него пихаем пробел?

**Comment by DarkKeks** [comment]
Попытался воспроизвести то, как показывает такие случаи `diff -u`
<img width="398" alt="image" src="https://user-images.githubusercontent.com/13303874/100283725-0ec3d800-2f7f-11eb-90be-2b698f9c0b12.png">
